---
- bin: sjson
  args:
    - --indent
    - "0"
  type: stream
  filetypes:
    - json
  install:
    pip:
      - sortd

- bin: scfg
  type: stream
  filetypes:
    - cfg
  install:
    pip:
      - sortd

- bin: isort
  type: stream
  args:
    - "-"
  filetypes:
    - python
  install:
    pip:
      - isort

- bin: black
  type: stream
  args:
    - "-"
  filetypes:
    - python
  install:
    pip:
      - black

- bin: prettier
  args:
    - --stdin-filepath
    - --
    - "%"
  type: stream
  filetypes:
    - css
    - html
    - javascript
    - javascript.jsx
    - json
    - javascriptreact
    - less
    - markdown
    - scss
    - typescript
    - typescript.tsx
    - typescriptreact
    - xml
    - yaml
  install:
    npm:
      - prettier

- bin: pg_format
  type: stream
  filetypes:
    - sql
  install:
    script:
      env:
        URI: https://github.com/darold/pgFormatter/archive/v4.4.tar.gz
      body: |-
        set -eu
        set -o pipefail

        NAME='pg_format'
        EXT='.tar.gz'

        BIN='bin'
        LIB='lib'
        TMP='tmp'

        EXEC="$BIN/$NAME"
        WGET_DEST="${TMP}/${NAME}${EXT}"
        TAR_DEST="$LIB/$NAME"


        if [[ -x "$EXEC" ]]
        then
          exit
        else
          mkdir -p "$TMP" "$BIN" "$LIB" "$TAR_DEST"
          wget "$URI" --output-document "$WGET_DEST"
          tar -xJvf "$WGET_DEST" --strip-components 1 --directory "$TAR_DEST"
          cat "$TAR_DEST"
          ln -s "../$TAR_DEST/$NAME" "$EXEC"
        fi

- bin: rustfmt
  type: stream
  filetypes:
    - rust

- bin: gofmt
  type: stream
  filetypes:
    - go
