---
- bin: sjson
  args:
    - --indent
    - "0"
  type: stream
  filetypes:
    - json
  install:
    pip:
      - sortd

- bin: scfg
  type: stream
  filetypes:
    - cfg
  install:
    pip:
      - sortd

- bin: isort
  type: stream
  args:
    - "-"
  filetypes:
    - python
  install:
    pip:
      - isort

- bin: black
  type: stream
  args:
    - "-"
  filetypes:
    - python
  install:
    pip:
      - black

- bin: prettier
  args:
    - --stdin-filepath
    - --
    - "%"
  type: stream
  filetypes:
    - css
    - html
    - javascript
    - javascript.jsx
    - json
    - javascriptreact
    - less
    - markdown
    - scss
    - typescript
    - typescript.tsx
    - typescriptreact
    - xml
    - yaml
  install:
    npm:
      - prettier

# - bin: docker
#   type: stream
#   args:
#     - run
#     - --rm
#     - --interactive
#     - --
#     - darold.net/pgformatter
#     - "-"
#   filetypes:
#     - sql

- bin: pg_format
  type: stream
  filetypes:
    - sql
  install:
    script:
      env:
        URI: https://github.com/darold/pgFormatter/archive/v4.4.tar.gz
      body: |-
        set -eu
        set -o pipefail

        URI="https://github.com/darold/pgFormatter/archive/v4.4.tar.gz"
        BIN='bin/pg_format'
        if [[ -x "$BIN" ]]
        then
          exit
        else
          TMP="tmp"
          DIR="$TMP/pg_format"
          FILE="$DIR.zip"
          mkdir -p "$TMP" "$DIR"
          wget "$URI" --output-document "$FILE"
          tar xJvf "$FILE" --strip-components 1 --directory "$DIR"

          cd "$DIR" || exit 1
          perl 'Makefile.PL' 'DESTDIR=.'
          make install
        fi


- bin: rustfmt
  type: stream
  filetypes:
    - rust

- bin: gofmt
  type: stream
  filetypes:
    - go
