---
- bin: fmt-json
  args:
    - "%"
  type: stream
  filetypes:
    - json
  install:
    pip:
      - sortd
    npm:
      - prettier

- bin: fmt-py
  type: stream
  filetypes:
    - python
  install:
    pip:
      - isort
      - black

- bin: scfg
  type: stream
  filetypes:
    - cfg
  install:
    pip:
      - sortd

- bin: prettier
  args:
    - --stdin-filepath
    - --
    - "%"
  type: stream
  filetypes:
    - yaml
    - xml
    - css
    - scss
    - less
    - html
    - markdown
    - javascript
    - javascriptreact
    - javascript.jsx
    - typescript
    - typescriptreact
    - typescript.tsx
  install:
    npm:
      - prettier

- bin: rustfmt
  type: stream
  filetypes:
    - rust

- bin: gofmt
  type: stream
  filetypes:
    - go
