---
- bin: sjson
  args:
    - --indent
    - "0"
  type: stream
  filetypes:
    - json
  install:
    pip:
      - sortd

- bin: prettier
  args:
    - --stdin-filepath
    - "%"
  type: stream
  filetypes:
    - json
  install:
    npm:
      - prettier

- bin: isort
  type: stream
  args:
    - "-"
  filetypes:
    - python
  install:
    pip:
      - isort

- bin: black
  type: stream
  args:
    - "-"
  filetypes:
    - python
  install:
    pip:
      - black

- bin: scfg
  type: stream
  filetypes:
    - cfg
  install:
    pip:
      - sortd

- bin: prettier
  args:
    - --stdin-filepath
    - --
    - "%"
  type: stream
  filetypes:
    - css
    - html
    - javascript
    - javascript.jsx
    - javascriptreact
    - less
    - markdown
    - scss
    - typescript
    - typescript.tsx
    - typescriptreact
    - xml
    - yaml
  install:
    npm:
      - prettier

- bin: rustfmt
  type: stream
  filetypes:
    - rust

- bin: gofmt
  type: stream
  filetypes:
    - go
