---
- bin: yamllint
  type: fs
  args:
    - --
    - ${filename}
  filetypes:
    - yaml
  install:
    pip:
      - yamllint

- bin: mypy
  type: fs
  args:
    - --
    - ${filename}
  filetypes:
    - python
  install:
    pip:
      - mypy

- bin: pylint
  type: fs
  args:
    - --
    - ${filename}
  filetypes:
    - python
  install:
    pip:
      - pylint

- bin: eslint
  type: fs
  args:
    - --
    - ${filename}
  filetypes:
    - javascript
    - javascript.jsx
    - javascriptreact
    - typescript
    - typescript.tsx
    - typescriptreact
  install:
    npm:
      - eslint

- bin: shellcheck
  type: fs
  args:
    - --
    - ${filename}
  filetypes:
    - sh
    - zsh
  install:
    script:
      env:
        URI_ROOT: https://github.com/koalaman/shellcheck/releases/download
        MAC_OS: v0.7.1/shellcheck-v0.7.1.darwin.x86_64.tar.xz
        LINUX: v0.7.1/shellcheck-v0.7.1.linux.x86_64.tar.xz
        ARCHIVED: shellcheck-v0.7.1/shellcheck
      body: |-
        set -eu
        set -o pipefail

        FILE="${TMP_DIR}/${BIN_NAME}.tar.xz"
        if [[ "$OS" == 'Darwin' ]]
        then
          PLATFORM="$MAC_OS"
        else
          PLATFORM="$LINUX"
        fi
        get "${URI_ROOT}/${PLATFORM}" --dest "$FILE"
        unpack "$FILE" "$TMP_DIR"
        mv "${TMP_DIR}/${ARCHIVED}" $BIN_PATH
        chmod +x "$BIN_PATH"

- bin: hadolint
  type: stream
  args:
    - "-"
  filetypes:
    - dockerfile
  install:
    script:
      env:
        MAC_OS: https://homebrew.bintray.com/bottles/hadolint-1.19.0.big_sur.bottle.tar.gz
        MAC_OS_EXC: hadolint/1.19.0/bin/hadolint
        LINUX: https://github.com/hadolint/hadolint/releases/download/v1.19.0/hadolint-Linux-x86_64
      body: |-
        set -eu
        set -o pipefail

        if [[ "$OS" == 'Darwin' ]]
        then
          FILE="${TMP_DIR}/${BIN_NAME}.tar.xz"
          get "$MAC_OS" --dest "$FILE"
          unpack "$FILE" "$TMP_DIR"
          mv "${TMP_DIR}/${MAC_OS_EXC}" "$BIN_PATH"
        else
          get "$LINUX" --dest "$BIN_PATH"
          chmod +x "$BIN_PATH"
        fi

- bin: markdownlint
  type: stream
  args:
    - --stdin
  filetypes:
    - markdown
  install:
    npm:
      - markdownlint-cli

- bin: alex
  type: fs
  args:
    - --
    - ${filename}
  filetypes:
    - markdown
  install:
    npm:
      - alex

- bin: proselint
  type: fs
  args:
    - --
    - ${filename}
  filetypes:
    - markdown
  install:
    pip:
      - proselint

- bin: write-good
  type: fs
  args:
    - ${filename}
  filetypes:
    - markdown
  install:
    npm:
      - write-good
