---
- bin: yamllint
  type: fs
  args:
    - --
    - "%"
  filetypes:
    - yaml
  install:
    pip:
      - yamllint

- bin: mypy
  type: fs
  args:
    - --
    - "%"
  filetypes:
    - python
  install:
    pip:
      - mypy

- bin: pylint
  type: fs
  args:
    - --
    - "%"
  filetypes:
    - python
  install:
    pip:
      - pylint

- bin: eslint
  type: fs
  args:
    - --
    - "%"
  filetypes:
    - javascript
    - javascript.jsx
    - javascriptreact
    - typescript
    - typescript.tsx
    - typescriptreact
  install:
    npm:
      - eslint

- bin: shellcheck
  type: fs
  args:
    - --
    - "%"
  filetypes:
    - sh
    - zsh

- bin: docker
  type: stream
  args:
    - run
    - --rm
    - --interactive
    - --
    - hadolint/hadolint
  filetypes:
    - dockerfile

- bin: docker
  type: stream
  args:
    - run
    - --rm
    - --interactive
    - --
    - darold.net/pgformatter
    - "-"
  filetypes:
    - sql

- bin: markdownlint
  type: stream
  args:
    - --stdin
  filetypes:
    - markdown
  install:
    npm:
      - markdownlint-cli

- bin: alex
  type: fs
  args:
    - --
    - "%"
  filetypes:
    - markdown
  install:
    npm:
      - alex

- bin: proselint
  type: fs
  args:
    - --
    - "%"
  filetypes:
    - markdown
  install:
    pip:
      - proselint

- bin: write-good
  type: fs
  args:
    - "%"
  filetypes:
    - markdown
  install:
    npm:
      - write-good
