---
- bin: mypy
  type: fs
  args:
    - --
    - "%"
  filetypes:
    - python
  install:
    pip:
      - mypy

- bin: shellcheck
  type: fs
  args:
    - --
    - "%"
  filetypes:
    - sh
    - zsh
