---
- bin: yamllint
  type: fs
  args:
    - --
    - ${filename}
  filetypes:
    - yaml
  install:
    pip:
      - yamllint

- bin: mypy
  type: fs
  args:
    - --
    - ${filename}
  filetypes:
    - python
  install:
    pip:
      - mypy

- bin: pylint
  type: fs
  args:
    - --
    - ${filename}
  filetypes:
    - python
  install:
    pip:
      - pylint

- bin: eslint
  type: fs
  args:
    - --
    - ${filename}
  filetypes:
    - javascript
    - javascript.jsx
    - javascriptreact
    - typescript
    - typescript.tsx
    - typescriptreact
  install:
    npm:
      - eslint

- bin: shellcheck
  type: fs
  args:
    - --
    - ${filename}
  filetypes:
    - sh
    - zsh
  install:
    script:
      required:
        - wget
        - tar
      env:
        URI_ROOT: https://github.com/koalaman/shellcheck/releases/download
        MAC_OS: v0.7.1/shellcheck-v0.7.1.darwin.x86_64.tar.xz
        LINUX: v0.7.1/shellcheck-v0.7.1.linux.x86_64.tar.xz
      body: |-
        set -eu
        set -o pipefail

        FILE="$TMP_DIR/${BIN_NAME}.tar.xz"
        if [[ "$(uname)" == 'Darwin' ]]
        then
          ARCH="$MAC_OS"
        else
          ARCH="$LINUX"
        fi
        wget "${URI_ROOT}/${ARCH}" --output-document "$FILE"
        tar -xJvf "$FILE"
        # chmod +x "$BIN_PATH"

- bin: docker
  type: stream
  args:
    - run
    - --rm
    - --interactive
    - --
    - hadolint/hadolint
  filetypes:
    - dockerfile

- bin: markdownlint
  type: stream
  args:
    - --stdin
  filetypes:
    - markdown
  install:
    npm:
      - markdownlint-cli

- bin: alex
  type: fs
  args:
    - --
    - ${filename}
  filetypes:
    - markdown
  install:
    npm:
      - alex

- bin: proselint
  type: fs
  args:
    - --
    - ${filename}
  filetypes:
    - markdown
  install:
    pip:
      - proselint

- bin: write-good
  type: fs
  args:
    - ${filename}
  filetypes:
    - markdown
  install:
    npm:
      - write-good
