---
- bin: mypy
  type: fs
  args:
    - --
    - "%"
  filetypes:
    - python
  install:
    pip:
      - mypy

- bin: markdownlint
  type: stream
  args:
    - --stdin
  filetypes:
    - markdown
  install:
    npm:
      - markdownlint-cli

- bin: shellcheck
  type: fs
  args:
    - --
    - "%"
  filetypes:
    - sh
    - zsh
