---
- server: diagnosticls
  bin: diagnostic-languageserver
  filetypes:
    - sh
  settings:
    initializationOptions:
      linters:
        shellcheck:
          sourceName: shellcheck
          command: shellcheck
          args:
            - --format
            - json
            - -
          debounce: 100
          parseJson:
            column: column
            endColumn: endColumn
            endLine: endLine
            line: line
            message: ${message} [${code}]
            security: level
          securities:
            error: error
            info: info
            style: hint
            warning: warning

      filetypes:
        sh:
          - shellcheck

  install:
    npm:
      - diagnostic-languageserver

- server: jsonls
  bin: vscode-json-languageserver
  filetypes:
    - json
  install:
    npm:
      - vscode-json-languageserver

- server: yamlls
  bin: yaml-language-server
  filetypes:
    - yaml
  install:
    npm:
      - yaml-language-server

- server: bashls
  bin: bash-language-server
  filetypes:
    - sh
    - zsh
  install:
    npm:
      - bash-language-server

- server: dockerls
  bin: docker-langserver
  filetypes:
    - dockerfile
  install:
    npm:
      - dockerfile-language-server-nodejs

- server: html
  bin: html-languageserver
  filetypes:
    - html
  install:
    npm:
      - vscode-html-languageserver-bin

- server: cssls
  bin: css-languageserver
  filetypes:
    - css
    - less
    - scss
  install:
    npm:
      - vscode-css-languageserver-bin

- server: pyright
  bin: pyright-langserver
  filetypes:
    - python
  install:
    npm:
      - pyright

- server: rust_analyzer
  bin: rust-analyzer
  filetypes:
    - rust

- server: gopls
  bin: gopls
  filetypes:
    - go
    - gomod

- server: sourcekit
  bin: xcrun
  filetypes:
    - c
    - cpp
    - objective-c
    - objective-cpp
    - swift

- server: sqlls
  bin: sql-language-server
  args:
    - up
    - --method
    - stdio
  filetypes:
    - sql
  install:
    npm:
      - sql-language-server

- server: tsserver
  bin: typescript-language-server
  filetypes:
    - javascript
    - javascript.jsx
    - javascriptreact
    - typescript
    - typescript.tsx
    - typescriptreact
  install:
    npm:
      - typescript
      - typescript-language-server

- server: r_language_server
  bin: R
  filetypes:
    - r
    - rmd

- server: vimls
  bin: vim-language-server
  filetypes:
    - vim
  install:
    npm:
      - vim-language-server
