---
- server: diagnosticls
  bin: diagnostic-languageserver
  filetypes:
    - sh

  init_options:
    linters:
      shellcheck:
        sourceName: shellcheck
        command: shellcheck
        args:
          - --format=json
          - --exclude=SC1090
          - "-"
        debounce: 100
        parseJson:
          column: column
          endColumn: endColumn
          endLine: endLine
          line: line
          message: ${message} [${code}]
          security: level
        securities:
          error: error
          info: info
          style: hint
          warning: warning

    filetypes:
      sh:
        - shellcheck

  install:
    npm:
      - diagnostic-languageserver

- server: jsonls
  bin: vscode-json-languageserver
  install:
    npm:
      - vscode-json-languageserver

- server: yamlls
  bin: yaml-language-server
  install:
    npm:
      - yaml-language-server

- server: bashls
  bin: bash-language-server
  install:
    npm:
      - bash-language-server

- server: dockerls
  bin: docker-langserver
  install:
    npm:
      - dockerfile-language-server-nodejs

- server: pyright
  bin: pyright-langserver
  install:
    npm:
      - pyright

- server: rust_analyzer
  bin: rust-analyzer
  install:
    script:
      env:
        URI_ROOT: https://github.com/rust-analyzer/rust-analyzer/releases/download
        MAC_OS: rust-analyzer-mac
        LINUX: rust-analyzer-linux
        RELEASE: "2020-12-28"
      body: |-
        set -eu
        set -o pipefail

        if [[ "$OS" == 'Darwin' ]]
        then
          ARCH="$MAC_OS"
        else
          ARCH="$LINUX"
        fi
        get "${URI_ROOT}/${RELEASE}/${ARCH}" --dest "$BIN_PATH"
        chmod +x "$BIN_PATH"

- server: gopls
  bin: gopls
  install:
    go:
      - golang.org/x/tools/gopls@latest

- server: sourcekit
  bin: xcrun

- server: sqlls
  bin: sql-language-server
  args:
    - up
    - --method
    - stdio
  install:
    npm:
      - sql-language-server

- server: rome
  bin: rome
  install:
    npm:
      - rome

- server: tsserver
  bin: typescript-language-server
  install:
    npm:
      - typescript
      - typescript-language-server

- server: html
  bin: html-languageserver
  install:
    npm:
      - vscode-html-languageserver-bin

- server: cssls
  bin: css-languageserver
  install:
    npm:
      - vscode-css-languageserver-bin

- server: graphqlls
  bin: graphql-lsp
  args:
    - server
  install:
    npm:
      - graphql-language-service-cli

- server: r_language_server
  bin: R

- server: vimls
  bin: vim-language-server
  install:
    npm:
      - vim-language-server
