---
- server: bashls
  bin: bash-language-server
  filetypes:
    - sh
    - zsh
  install:
    npm:
      - bash-language-server

- server: cssls
  bin: css-languageserver
  filetypes:
    - css
    - scss
    - less
  install:
    npm:
      - vscode-css-languageserver-bin

- server: dockerls
  bin: docker-langserver
  filetypes:
    - dockerfile
  install:
    npm:
      - dockerfile-language-server-nodejs

- server: gopls
  bin: gopls
  filetypes:
    - go
    - gomod

- server: html
  bin: html-languageserver
  filetypes:
    - html
  install:
    npm:
      - vscode-html-languageserver-bin

- server: jsonls
  bin: vscode-json-languageserver
  filetypes:
    - json
  install:
    npm:
      - vscode-json-languageserver

- server: pyright
  bin: pyright-langserver
  filetypes:
    - python
  install:
    npm:
      - pyright

- server: r_language_server
  bin: R
  filetypes:
    - r
    - rmd

- server: rust_analyzer
  bin: rust-analyzer
  filetypes:
    - rust

- server: sqlls
  bin: sql-language-server
  args:
    - up
    - --method
    - stdio
  filetypes:
    - sql
  install:
    npm:
      - sql-language-server

- server: sourcekit
  bin: xcrun
  filetypes:
    - swift
    - c
    - cpp
    - objective-c
    - objective-cpp

- server: tsserver
  bin: typescript-language-server
  filetypes:
    - javascript
    - javascriptreact
    - javascript.jsx
    - typescript
    - typescriptreact
    - typescript.tsx
  install:
    npm:
      - typescript
      - typescript-language-server

- server: vimls
  bin: vim-language-server
  filetypes:
    - vim
  install:
    npm:
      - vim-language-server

- server: yamlls
  bin: yaml-language-server
  filetypes:
    - yaml
  install:
    npm:
      - yaml-language-server
