---
- uri: https://github.com/ms-jpq/chadtree
  keys:
    - modes: n
      maps:
        "<leader>v": "<cmd>CHADopen<cr>"

- uri: https://github.com/ms-jpq/kok.nvim
  settings:
    completefunc:
      val: KoKomnifunc

- uri: https://github.com/neovim/nvim-lspconfig
  keys:
    - modes: n
      maps:
        "H": "<cmd>lua vim.lsp.util.show_line_diagnostics()<cr>"
        "K": "<cmd>lua vim.lsp.buf.hover()<cr>"
        "L": "<cmd>lua vim.lsp.buf.code_action()<cr>"
        "R": "<cmd>lua vim.lsp.buf.rename()<cr>"
        "gp": "<cmd>lua vim.lsp.buf.definition()<cr>"
        "gP": "<cmd>lua vim.lsp.buf.references()<cr>"
        "gl": "<cmd>lua vim.lsp.buf.declaration()<cr>"
        "gL": "<cmd>lua vim.lsp.buf.implementation()<cr>"
        "go": "<cmd>lua vim.lsp.buf.signature_help()<cr>"
        "gO": "<cmd>lua vim.lsp.buf.type_definition()<cr>"
        "ge": "<cmd>lua vim.lsp.buf.document_symbol()<cr>"
        "gE": "<cmd>lua vim.lsp.buf.workspace_symbol()<cr>"
        "g[": "<cmd>lua vim.lsp.diagnostic.goto_prev()<cr>"
        "g]": "<cmd>lua vim.lsp.diagnostic.goto_next()<cr>"
  lua: |-
    lv = lv or {}
    lv.lsp = require "lspconfig"

- uri: https://github.com/junegunn/fzf

- uri: https://github.com/junegunn/fzf.vim
  vals:
    fzf_buffers_jump: True
    fzf_preview_window: right:wrap
    fzf_layout:
      window:
        width: 0.9
        height: 0.9
  keys:
    - modes: n
      maps:
        "<c-p>": "<cmd>Commands<cr>"
        "<c-n>": "<cmd>History:<cr>"
        "<leader>p": "<cmd>Files<cr>"
        "<leader>P": "<cmd>History<cr>"
        "<leader>o": "<cmd>BLines<cr>"
        "<leader>I": "<cmd>Buffers<cr>"
    - modes: n
      opts:
        silent: False
      maps:
        "<leader>O": ":Rg "
  lua: |-
    vim.env["FZF_DEFAULT_OPTS"] = vim.env["FZF_DEFAULT_OPTS"] .. " --no-border"

- uri: https://github.com/sainnhe/edge
  vals:
    edge_style: neon
    edge_menu_selection_background: purple

- uri: https://github.com/itchyny/lightline.vim
  vals:
    lightline:
      colorscheme: edge

- uri: https://github.com/liuchengxu/vim-which-key
  keys:
    - modes: n
      maps:
        "<leader>": "<cmd>WhichKey '<space>'<cr>"
        "[": "<cmd>WhichKey '['<cr>"
        "]": "<cmd>WhichKey ']'<cr>"

- uri: https://github.com/wellle/targets.vim

- uri: https://github.com/tpope/vim-repeat

- uri: https://github.com/tpope/vim-surround

- uri: https://github.com/tpope/vim-commentary

- uri: https://github.com/junegunn/vim-easy-align
  keys:
    - modes: n
      opts:
        noremap: False
      maps:
        "ga": "<plug>(EasyAlign)"

- uri: https://github.com/Raimondi/delimitMate

- uri: https://github.com/tpope/vim-sleuth

- uri: https://github.com/airblade/vim-gitgutter

- uri: https://github.com/sheerun/vim-polyglot

- uri: https://github.com/ms-jpq/kok-snippets

- uri: https://github.com/ms-jpq/kok-t9
  keys:
    - modes: n
      maps:
        "gz": "<cmd>KoKstart<cr>"

- uri: https://github.com/honza/vim-snippets

- uri: https://github.com/Shougo/neosnippet-snippets
